version: "3.3"

services:
  prod:
    container_name: kavanet-client-production
    build:
      context: . # this folder
      dockerfile: Dockerfile.prod
    ports:
      # - 5001:5001
      # - 4000:4000
      - 80:80
