version: "3.5"
services:
  kavanet-client:
    container_name: kavanet-client
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: kavanet-client:latest
    volumes: 
      - ".:/home/app" # copy everything to app inside container
      - "/home/app/node_modules" # Ignore node modules
    ports: # Only needed for inward ports
      - 3001:3000 
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables hot reloading
    networks:
      - proxynet

networks:
  proxynet:
    name: kavanet-network

