version: "3.5"
services:
  kavanet-client:
    container_name: kavanet-client
    build:
      context: .
      dockerfile: Dockerfile
    image: kavanet-client:latest
    volumes: 
      - ".:/usr/apps" # copy everything to app inside container
      - "/usr/apps/node_modules" # Ignore node modules
    ports: # Only needed for inward ports
      - 3001:3000 
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables hot reloading
    networks:
      - proxynet

networks:
  proxynet:
    name: kavanet-network

